version: 2

defaults:
  working_directory: /tmp

references: 
  container_config: &container_config
    docker:
      - image: circleci/node:carbon-stretch-browsers-legacy

jobs:
  build:
    <<: *container_config
    steps: 
      - checkout
      - restore_cache:
          key: dependency-node-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: yarn
      - run:
          name: Build
          command: yarn run build
      - save_cache:
          key: dependency-node-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
